services:
  db:
    container_name: workout_db
    image: postgres:17.5-alpine
    volumes:
      - "./database/postgres/data:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
  
